name: Daily security audit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    if: github.repository == 'foundationdb-rs/foundationdb-rs'
    steps:
      - name: Install FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.3.0
        with:
          version: "7.1.37"
      - uses: actions/checkout@v5.0.0
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}