name: "Nix checks"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: cachix/install-nix-action@v31
      - run: nix flake check
      - name: Building crate with Nix
        run: nix develop -c cargo build -p bindingtester
