name: PR correctness

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled, unlabeled, opened, synchronize, reopened ]

jobs:
  bindingtester:
    if: contains(github.event.pull_request.labels.*.name, 'correctness')
    name: Binding Tester
    runs-on: ubuntu-latest

    strategy:
      matrix:
        parallelism: ["1", "2", "3"]
        toolchain: ["1.82.0", "stable", "beta", "nightly"]
    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          submodules: recursive

      - name: Setup FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.3.0
        with:
          version: "7.4.3"

      # Setting up a fixed Python version because of https://github.com/foundationdb-rs/foundationdb-rs/issues/226
      - name: Setup fixed Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Enable tenant
        run: fdbcli --exec "configure single memory tenant_mode=optional_experimental"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build
        run: cargo build -p bindingtester

      - name: Setup bindingtester
        run: scripts/setup_bindingtester.sh target/debug/bindingtester

      - name: Run bindingtester
        run: scripts/run_bindingtester.sh 1000
