name: rustdoc
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Setup FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.3.0
        with:
          version: "7.4.3"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build Documentation
        run: cargo doc --no-deps --features num-bigint,embedded-fdb-include,tenant-experimental,fdb-7_4

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
